In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install statistics

Defaulting to user installation because normal site-packages is not writeable
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for statistics: filename=statistics-1.0.3.5-py3-none-any.whl size=7450 sha256=2ab1ea8b8843f8ae73f480067d93978410a16c985766635c825d7e71b68cd3cb
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\10\9c\1a\0c68a89e4533a18e9f9902018b94ffc2481139818b67cbb05a
Successfully built statistics
Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd
import numpy as np
import statistics

In [36]:
#loading data set
df = pd.read_csv("Indian_Cricket_Team_Dataset.csv")

In [37]:
age_array = df['Age'].to_numpy()

print(age_array)

[26 23 32 34 30 27 32 24 26 29 22 26 30 30 27 24 23 27 27 22 25 24 21 27
 31 33 25 21 35 31 24 20 31 29 25 32 31 28 20 30 30 34 29 35 31 31 35 34
 33 33 34 33 22 31 26 23 35 28 22 24 22 26 24 28 26 21 23 28 31 33 21 29
 28 29 24 21 23 31 34 31 26 31 32 27 34 22 33 20 23 21 27 23 21 33 25 25
 29 23 25 32 34 21 29 31 21 29 33 23 33 34 35 34 27 33 26 31 28 33 27 24
 35 32 21 34 24 27 29 28 31 31 31 32 28 32 34 32 20 28 26 28 27 20 31 27
 27 34 30 22 20 27 22 22 20 30 24 29 26 29 28 31 26 28 27 31 21 20 35 26
 26 33 27 24 22 31 27 25 30 22 20 22 24 34 33 22 20 24 29 26 34 33 26 30
 28 34 34 29 29 31 32 22 34 35 26 20 23 32 35 23 33 24 26 26 32 34 30 32
 23 32 35 26 30 22 25 31 21 29 32 33 28 24 25 31 31 31 31 23 33 33 30 35
 29 26 31 28 26 33 20 20 28 30 33 28 23 32 28 22 26 25 27 30 28 33 24 20
 22 29 31 27 34 30 25 35 35 27 28 23 20 33 20 29 23 31 33 26 21 22 20 24
 20 27 20 30 20 21 21 31 25 26 24 35 20 20 22 33 21 24 31 29 35 25 35 26
 23 26 30 27 30 20 34 25 27 24 23 21 25 25 30 34 35

In [40]:
# Calculate the average age
average_age = df['Age'].mean()
# Print the average age
print(f"The average age of the players is: {average_age:.2f} years")

The average age of the players is: 27.57 years


In [41]:
# Find the oldest and youngest player ages
oldest_age = df['Age'].max()
youngest_age = df['Age'].min()

# Print the results
print(f"The oldest player is {oldest_age} years old.")
print(f"The youngest player is {youngest_age} years old.")

The oldest player is 35 years old.
The youngest player is 20 years old.


In [42]:
# Count the number of players above 30 years old
players_above_30 = df[df['Age'] > 30].shape[0]

# Print the result
print(f"The total number of players above 30 years old is: {players_above_30}")

The total number of players above 30 years old is: 336


In [43]:
# Calculate the median batting average
median_batting_avg = df['Batting Average'].median()

# Print the result
print(f"The median batting average is: {median_batting_avg:.2f}")

The median batting average is: 40.13


In [44]:
# Calculate the standard deviation of strike rates
strike_rate_std = df['Strike Rate'].std()

# Print the result
print(f"The standard deviation of strike rates is: {strike_rate_std:.2f}")

The standard deviation of strike rates is: 29.12


In [45]:
# Calculate the 90th percentile of batting average
percentile_90 = df['Batting Average'].quantile(0.90)

# Print the result
print(f"The 90th percentile of batting average is: {percentile_90:.2f}")

The 90th percentile of batting average is: 55.32


In [46]:
# Count the number of players with strike rate above 150
players_above_150_sr = df[df['Strike Rate'] > 150].shape[0]

# Print the result
print(f"The number of players with a strike rate above 150 is: {players_above_150_sr}")

The number of players with a strike rate above 150 is: 513


In [47]:
# Extract the first 20 batting averages
first_20_batting_avgs = df['Batting Average'].head(20).values

# Reshape the first 20 batting averages into a 4x5 matrix
batting_avg_matrix = first_20_batting_avgs.reshape(4, 5)

# Print the reshaped matrix
print("4x5 Matrix of the first 20 batting averages:")
print(batting_avg_matrix)

4x5 Matrix of the first 20 batting averages:
[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]


In [48]:
# Extract the first 20 batting averages
first_20_batting_avgs = df['Batting Average'].head(20).values

# Reshape the first 20 batting averages into a 4x5 matrix
batting_avg_matrix = first_20_batting_avgs.reshape(4, 5)

# Compute the row-wise sum of the reshaped matrix
row_sums = np.sum(batting_avg_matrix, axis=1)

# Print the reshaped matrix and the row-wise sums
print("4x5 Matrix of the first 20 batting averages:")
print(batting_avg_matrix)
print("\nRow-wise sums of the matrix:")
print(row_sums)

4x5 Matrix of the first 20 batting averages:
[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]

Row-wise sums of the matrix:
[190.79 193.1  212.87 210.42]


In [49]:
# Extract the first 20 batting averages
first_20_batting_avgs = df['Batting Average'].head(20).values

# Reshape the first 20 batting averages into a 4x5 matrix
batting_avg_matrix = first_20_batting_avgs.reshape(4, 5)

# Compute the column-wise mean of the reshaped matrix
column_means = np.mean(batting_avg_matrix, axis=0)

# Print the reshaped matrix and the column-wise means
print("4x5 Matrix of the first 20 batting averages:")
print(batting_avg_matrix)
print("\nColumn-wise means of the matrix:")
print(column_means)

4x5 Matrix of the first 20 batting averages:
[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]

Column-wise means of the matrix:
[30.5325 35.3575 39.9775 51.2875 44.64  ]


In [50]:
# Extract the first 20 batting averages
first_20_batting_avgs = df['Batting Average'].head(20).values

# Reshape the first 20 batting averages into a 4x5 matrix
batting_avg_matrix = first_20_batting_avgs.reshape(4, 5)

# Transpose the reshaped matrix
transposed_matrix = batting_avg_matrix.T

# Print the original and transposed matrices
print("Original 4x5 Matrix:")
print(batting_avg_matrix)
print("\nTransposed 5x4 Matrix:")
print(transposed_matrix)

Original 4x5 Matrix:
[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]

Transposed 5x4 Matrix:
[[27.7  22.2  34.59 37.64]
 [24.61 38.21 42.43 36.18]
 [36.87 40.9  39.24 42.9 ]
 [51.81 45.78 55.4  52.16]
 [49.8  46.01 41.21 41.54]]


In [51]:
# Calculate the variance of batting average
variance_batting_avg = df['Batting Average'].var()

# Print the result
print(f"The variance of batting average is: {variance_batting_avg:.2f}")

The variance of batting average is: 131.67


In [52]:
# Extract the 'Age' and 'Matches Played' columns
age = df['Age'].values
matches_played = df['Matches Played'].values

# Stack the two columns horizontally
stacked_array = np.column_stack((age, matches_played))

# Print the stacked array
print("Stacked array of Age and Matches Played:")
print(stacked_array)

Stacked array of Age and Matches Played:
[[ 26 456]
 [ 23 154]
 [ 32 210]
 ...
 [ 23 126]
 [ 35  16]
 [ 30 146]]


In [53]:
# Extract the 'Batting Average' column as a NumPy array
batting_avg_array = df['Batting Average'].values

# Split the batting average array into 5 equal parts
split_arrays = np.array_split(batting_avg_array, 5)

# Print the split arrays
for i, arr in enumerate(split_arrays):
    print(f"Part {i + 1}:")
    print(arr)

Part 1:
[27.7  24.61 36.87 51.81 49.8  22.2  38.21 40.9  45.78 46.01 34.59 42.43
 39.24 55.4  41.21 37.64 36.18 42.9  52.16 41.54 46.47 49.51 40.81 37.07
 55.07 36.7  38.48 59.61 20.01 27.42 35.36 57.3  22.8  20.38 22.11 23.54
 21.5  39.19 43.23 30.87 35.93 23.67 33.45 40.9  49.29 20.13 38.69 31.88
 54.11 48.62 43.56 31.09 56.41 21.8  24.38 35.67 24.98 58.26 51.92 30.36
 43.54 59.29 55.37 44.03 56.15 59.57 49.73 22.6  36.06 53.51 29.22 53.23
 24.81 21.88 35.36 21.47 58.29 53.05 52.03 45.19 28.65 40.73 43.89 41.
 30.41 40.61 39.65 59.85 55.9  38.54 44.92 49.91 21.39 55.8  54.41 38.3
 35.65 30.92 39.07 21.78 54.09 21.42 33.16 57.26 49.41 31.26 30.11 20.2
 47.83 21.95 41.3  58.48 24.38 55.78 59.66 22.46 55.32 40.64 56.26 42.85
 46.48 41.75 54.58 49.36 40.85 54.73 29.81 26.29 26.42 33.36 29.55 57.2
 24.23 47.96 27.57 55.27 58.45 38.62 55.16 20.21 52.8  29.15 56.35 20.04
 42.25 50.27 30.35 27.73 23.36 33.06 42.39 24.63 35.07 20.36 52.75 25.14
 31.33 20.74 37.29 53.6  35.69 27.18 50.15 51.55